addons:
  chrome: stable
language: node_js
sudo: false
node_js: 10.21
python: 3.6
cache: pip
env:
  - TOXENV="py36_django20"
install:
  - sudo curl --output /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
  - pip install --user --upgrade pip setuptools --quiet
  - pip install -U -r --user requirements.txt --trusted-host dist.pinaxproject.com --quiet
  - pip install --user Image --quiet
  - pip install --user tox --quiet
script:
  - tox -e $TOXENV
