addons:
  chrome: stable
language: python
sudo: false
python: 3.6
cache: pip
env:
  - TOXENV="py36_django20"
install:
  - sudo curl --output /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
  - pip install --upgrade pip setuptools --quiet
  - pip install -U -r requirements.txt --trusted-host dist.pinaxproject.com --quiet
  - pip install Image --quiet
  - pip install tox --quiet
script:
  - tox -e $TOXENV
